### PR TITLE
Removed code in excess

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by Ocramius** [comment]
:+1:

**Comment by Slamdunk** [comment]
Ooops, meant another thing, wait

**Comment by Slamdunk** [comment]
Damn, you are too fast

**Comment by Slamdunk** [comment]
The parenthesis is right, the indentation is lacking

**Comment by Ocramius** [comment]
@Slamdunk I had intentionally kept the indentation broken - closing brace was distracting

**Pull request merged**
